### ISSUE TITLE
[BE] 주문하기 구현

### ISSUE THREAD

**Issue by kyupid** [kyupid/sidedish#46]
- [x] 주문을 생성한다고 생각하면 POST 방식이네?
- [x] 어떤 데이터를 받아야할까? (무엇을 주문, 몇개 주문,  누가 주문)
- [x] URL 뭘로?

---

내일 해야할건데,  미리 알려드리고 가면 좋을거 같아서 태그합니다.
URL 어떻게 되면 좋을까요?

@17-sss  @eve712

**Comment by 17-sss** [comment]
- 무엇을 주문 --> 각 상품의 id (hash가 될 수도 있는) 로 판별
  -  id는 상품의 primary key나 unique..로?
- 몇개를 주문 --> 상세정보창에서 선택한 **수량정보**를 서버로 전달.
- 누가 주문 --> OAuth를 적용한다면 그 유저의 고유 키 값을?

음 URL은 ` /buyProduct ` ..?  (POST)

다른 필요한 정보는 POST요청 보내면서 
formData로 전송해주면 될 것 같기도하고
아니면 input 데이터 값을 정제해서 저희쪽에서 보내도 될 것 같기도 하네욤

최대한 머릿속을 짜내보긴했는데.. 참고만 부탁드립니다!
확실한 정보가 아닐수도 있으니까요! (졸린눈 라노)

**Comment by kyupid** [comment]
URL: 
`POST` /order

JSON:
```js
{
  "client_id": "test-id",
  "detail_hash": "HBD98",
  "qty": 3
}
```

**Comment by kyupid** [comment]
{
    "client_id": "eve",
    "detail_hash": "HBD98",
    "quantity": 2
}
